HotelBedsApp/Controllers/passengersController.cs
using com.hotelbeds.distribution.hotel_api_model.auto.messages;
using com.hotelbeds.distribution.hotel_api_sdk;
using com.hotelbeds.distribution.hotel_api_sdk.helpers;
using HotelBedsApp.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
 

namespace HotelBedsApp.Controllers
{
    public class passengersController : Controller
    {
        //
        // GET: /passengers/

        public ActionResult Index()
        {
           
            SearchCriteriaViewModel searchcriteria = (SearchCriteriaViewModel)Session["SearchCriteria"];
            return View(searchcriteria);
        }
        [HttpPost]
        public ActionResult Index(FormCollection form,SearchCriteriaViewModel searchcriteria )
        {
            try
            {
                string[] type = form["pas.type"].Split(',');
                string[] age = form["pas.age"].Split(',');
                string[] name = form["pas.name"].Split(',');
                string[] surname = form["pas.surname"].Split(',');
                string[] roomId = form["pas.roomId"].Split(',');

                HotelApiClient client = new HotelApiClient();
                ConfirmRoom confirmRoom = new ConfirmRoom();
                confirmRoom.details = new List<RoomDetail>();
                for (int i = 0; i < type.Count(); i++)
                    confirmRoom.details.Add(new RoomDetail((com.hotelbeds.distribution.hotel_api_sdk.helpers.RoomDetail.GuestType)Enum.Parse(typeof(com.hotelbeds.distribution.hotel_api_sdk.helpers.RoomDetail.GuestType), type[i]), int.Parse(age[i]), name[i], surname[i], int.Parse(roomId[i])));

                string rateKey = (string)Session["ratekey"];
                BookingCheck bookingCheck = new BookingCheck();
                bookingCheck.addRoom(rateKey, confirmRoom);
                CheckRateRQ checkRateRQ = bookingCheck.toCheckRateRQ();

                if (checkRateRQ != null)
                {
                    CheckRateRS responseRate = client.doCheck(checkRateRQ);
                    if (responseRate != null && responseRate.error == null)
                    {
                        com.hotelbeds.distribution.hotel_api_sdk.helpers.Booking booking = new com.hotelbeds.distribution.hotel_api_sdk.helpers.Booking();
                        booking.createHolder("Rosetta", "Pruebas");
                        booking.clientReference = "SDK Test";
                        booking.remark = "***SDK***TESTING";

                        booking.addRoom(rateKey, confirmRoom);
                        BookingRQ bookingRQ = booking.toBookingRQ();
                        if (bookingRQ != null)
                        {
                            BookingRS responseBooking = client.confirm(bookingRQ);

                            if (responseBooking != null && responseBooking.error == null && responseBooking.booking != null)

                                ViewBag.BookingRef = responseBooking.booking.reference;


                        }
                        else
                        {
                            if (responseRate.error != null)
                            {
                                ViewBag.Error = responseRate.error.message;


                            }
                        }
                    }
                }


                return View(searchcriteria);
            }
            catch (Exception exp)
            { return Content(exp.Message); }
        }
    }

                    }

HotelBedsApp/Views/passengers/Index.cshtml
@model HotelBedsApp.ViewModel.SearchCriteriaViewModel
@{
    ViewBag.Title = "Passenger";
}

<h2>Passenger</h2>

@using (Html.BeginForm("Index","passengers"))
{
    @Html.ValidationSummary(true)
    if( Model.Passengers != null)
    {  
    <fieldset>
        <legend>Room 1:  Passengers</legend>
         
       @foreach(var pas in  Model.Passengers  )
       {
           var counter = 0;
        <div class="editor-label">
            Type
        </div>
            <div class="editor-field">
                @Html.EditorFor(model => pas.type, new { id = "pas-@counter.type", name = "pas-@counter.type" })

            </div>
    <div class="editor-label">
       Age
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => pas.age, new { id = "pas-@counter.age", name = "pas-@counter.age" })

    </div>
            <div class="editor-label">
                Name
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => pas.name, new { id = "pas-@counter.name", name = "pas-@counter.name" })
                
            </div>

    <div class="editor-label">
        Surname
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => pas.surname, new { id = "pas-@counter.surname", name = "pas-@counter.surname" })
        <input id="pas.roomId" name="pas.roomId" type="hidden" value="@pas.roomId" />
    </div>
             

            }

            <p>
                <input type="submit" value="Book Hotel" />
            </p>

            <div>
            </div>
</fieldset>
    }
    } 
            
              @if  (!string.IsNullOrEmpty(@ViewBag.Error))
              { <text>Error : </text> @ViewBag.Error}
              else
              {<text>Reference number</text> @ViewBag.BookingRef  }
          
       
         

 
@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@