HotelBedsApp/Controllers/resultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
 
using System.Diagnostics;
using com.hotelbeds.distribution.hotel_api_sdk.helpers;
using com.hotelbeds.distribution.hotel_api_model.auto.messages;
using HotelBedsApp.ViewModel;
using com.hotelbeds.distribution.hotel_api_sdk;
namespace HotelBedsApp.Controllers
{
    public class resultController : Controller
    {
        //
        // GET: /result/

        public ActionResult Index()
        {
            try
            {
                HotelApiClient client = new HotelApiClient();
                StatusRS status = client.status();

                SearchCriteriaViewModel searchcriteria = (SearchCriteriaViewModel)Session["SearchCriteria"];

                List<Tuple<string, string>> param;


                Availability avail = new Availability();
                avail.checkIn = searchcriteria.CheckInDate;
                avail.checkOut = searchcriteria.CheckOutDate;
                avail.destination = searchcriteria.DestinationCode;
                avail.zone = searchcriteria.Zone;
                // avail.zone = 90;
                // avail.language = "CAS";
                if (searchcriteria.NumberOfRooms >= 1)
                {
                    AvailRoom room = new AvailRoom();
                    room.adults = searchcriteria.RoomOneAdults;
                    room.children = searchcriteria.RoomOneChildren + searchcriteria.RoomOneInfants;
                    room.details = new List<RoomDetail>();
                    for (int i = 0; i < searchcriteria.RoomOneAdults; i++)
                    { room.adultOf(30); }

                    for (int i = 0; i < searchcriteria.RoomOneChildren; i++)
                    { room.childOf(11); }

                    for (int i = 0; i < searchcriteria.RoomOneInfants; i++)
                    { room.childOf(2); }

                    //room.childOf(4);                
                    avail.rooms.Add(room);
                }
                avail.payed = Availability.Pay.AT_WEB;
                //avail.ofTypes = new HashSet<hotel_api_model.auto.common.SimpleTypes.AccommodationType>();
                //avail.ofTypes.Add(hotel_api_model.auto.common.SimpleTypes.AccommodationType.HOTEL);
                //avail.ofTypes.Add(hotel_api_model.auto.common.SimpleTypes.AccommodationType.APARTMENT);

                avail.minCategory = searchcriteria.StarRatingSearch;
                //avail.limitHotelsTo = 10;
                //avail.numberOfTripAdvisorReviewsHigherThan = 2;
                //avail.tripAdvisorScoreHigherThan = 2

                //avail.matchingKeywords = new HashSet<int>();
                //avail.matchingKeywords.Add(34);
                //avail.matchingKeywords.Add(81);
                //avail.keywordsMatcher = Availability.Matcher.ALL;

                //avail.includeHotels = new List<int>();
                //avail.includeHotels.Add(111637);
                //avail.includeHotels.Add(2818);
                //avail.includeHotels.Add(138465);
                //avail.includeHotels.Add(164471);

                //avail.excludeHotels = new List<int>();
                //avail.excludeHotels.Add(187013);
                //avail.excludeHotels.Add(188330);

                //avail.useGiataCodes = false;
                //avail.limitHotelsTo = 250;
                //avail.limitRoomsPerHotelTo = 5;
                //avail.limitRatesPerRoomTo = 5;
                //avail.ratesHigherThan = 50;
                //avail.ratesLowerThan = 350;

                //avail.hbScoreHigherThan = 3;
                //avail.hbScoreLowerThan = 5;
                //avail.numberOfHBReviewsHigherThan = 50;

                //avail.tripAdvisorScoreHigherThan = 1;
                //avail.tripAdvisorScoreLowerThan = 4;
                //avail.numberOfHBReviewsHigherThan = 50;

                //avail.withinThis = new Availability.Circle() { latitude = 2.646633999999949, longitude = 39.57119, radiusInKilometers = 50 };
                //avail.withinThis = new Availability.Square() { northEastLatitude = 45.37680856570233, northEastLongitude = -2.021484375, southWestLatitude = 38.548165423046584, southWestLongitude = 8.658203125 };

                //avail.includeBoards = new List<string>();
                //avail.includeBoards.Add("R0-E10");
                //avail.includeBoards.Add("BB-E10");
                //avail.excludeBoards = new List<string>();
                //avail.excludeBoards.Add("RO");

                //avail.includeRoomCodes = new List<string>();
                //avail.includeRoomCodes.Add("DBL.ST");
                //avail.includeRoomCodes.Add("DBL.SU");
                ////avail.includeRoomCodes.AddRange(new string[]{ "DBL.ST", "DBL.SU" });
                //avail.excludeRoomCodes = new List<string>();
                //avail.excludeRoomCodes.Add("TPL.ST");

                AvailabilityRQ availabilityRQ = avail.toAvailabilityRQ();
                if (availabilityRQ == null)
                    throw new Exception("Availability RQ can't be null", new ArgumentNullException());
                Stopwatch sw = new Stopwatch();
                sw.Start();
                AvailabilityRS responseAvail = client.doAvailability(availabilityRQ);
                sw.Stop();
                ViewBag.TimeTaken = sw.Elapsed.Seconds;


                //  request.PathToSaveXml = Server.MapPath("~");




                if (responseAvail != null && responseAvail.hotels != null && responseAvail.hotels.hotels != null && responseAvail.hotels.hotels.Count > 0)
                {

                    Session["ResultedHotels"] = responseAvail.hotels;

                }

                return View(responseAvail);
            }
            catch (Exception exp)
            { return Content(exp.Message); }
        }
        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            
            string  ratekey = form[1] ;
          //  List<Hotel> hotels = (List<Hotel>)Session["ResultedHotels"];
            // Hotel selectedhotel=null;
          
            //foreach (string selectedroomtype in arrselectedroomtypes)
            //{
            //    string[] arrselectedroomtype = selectedroomtype.Split('-');
              
            //    if (selectedhotel == null)
            //    {
            //        hotelid = arrselectedroomtype[0];
            //        selectedhotel= hotels.Where (hotel=> hotel.HotelID ==hotelid ).FirstOrDefault (); 
                                    
            //       }

            //    int roomid = int.Parse (arrselectedroomtype[1]);
            //    string roomtypeid =  arrselectedroomtype[2] ;
                
            //     var bookroomtype= (from room in selectedhotel.Rooms 
            //                      from roomtype in room.RoomTypes 
            //                      where room.RoomCount == roomid && roomtype.Id == roomtypeid 
            //                      select roomtype).FirstOrDefault ();
            //     selectedhotel.Rooms[roomid - 1].BookRoomTypes = new List<RoomType>();
            //     selectedhotel.Rooms[roomid - 1].BookRoomTypes.Add(bookroomtype);
            
            //}
            Session["ratekey"] = ratekey;

            return RedirectToAction("Index", "passengers");
        }
    }
}

HotelBedsApp/Views/result/Index.cshtml
@model   com.hotelbeds.distribution.hotel_api_model.auto.messages.AvailabilityRS

@{
    ViewBag.Title = "Result";
}

<h2>Results (@Model.hotels.hotels.Count()) : Time Taken (@ViewBag.TimeTaken)</h2>
@section customhead
{
    <script type="text/javascript">

        $(document).ready(function () {

            $(".frm").on("submit", function () {

                var hotelcode = $(this).attr("hotelcode");

                var bookedroomids = "";
                $('input[name^="roomtype-' + hotelcode + '"]:checked').each(function (index, selectedroomtype) {


                    var roomcode = $(this).attr("roomcode");
                    var roomratekey = $(this).attr("roomratekey");
                    bookedroomids = roomratekey ;

                });
                
                $("#hdnBookedRoomID-" + hotelcode).val(bookedroomids);

            });

        });
        
   
   </script>

}


  

@foreach (var hotel in Model.hotels.hotels)
{
    using (Html.BeginForm("Index", "result", FormMethod.Post, new { id="frm-@hotel.code", @class="frm" ,name="frm-@hotel.code", hotelcode="@hotel.code",data_ajax="false"})) 
    {//<form id="frm-@hotel.code" class="frm" name="frm-@hotel.code" hotelcode="@hotel.code" action="@Url.Action("Index", "result")" method="post" data-ajax="false">
        <table>
            <tr>
                <td></td>
            </tr>
            <tr>
                <td>
                    <table>
                        <tr>
                            <td>
                                <strong>Hotel:@hotel.code  </strong> @hotel.name     (@hotel.categoryName*)  (@hotel.currency )

                                @*<input id="hdnBookedRoomID-@hotel.code" name="hdnBookedRoomID-@hotel.code" type="hidden" />*@
                                @*<p>@hotel.ShortDescription</p>*@
                            </td>
                            <td>
                                @*<img src ="@hotel.imageUrl"   alt = "@hotel.Name" />*@
                            </td>
                        </tr>
                        @*@if (@hotel.pOffers != null && @hotel.Offers.Count > 0)
                            {
                            <tr>
                            <td>
                            <strong>Offers</strong>
                            </td>
                            </tr>
                                foreach (var offer in hotel.Offers)
                                { <tr>
                            <td>
                            @offer
                            </td>
                            </tr>
                                }
                            }*@
                    </table>
                    @{string rateKey = string.Empty;
                    for (int r = 0; r < hotel.rooms.Count && String.IsNullOrEmpty(rateKey); r++)
                    {
                        var room = hotel.rooms[r];

                        <table>
                            <tr>
                                <td colspan="2">
                                    <strong>Room :</strong>@room.code
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    @*@{if (room.paxes != null)
                                          { <strong> Passengers :</strong>


                                        var adults= room.paxes.Where (p=> p.type.ToString()=="AD");
                                         var children = room.paxes.Where(p => p.type.ToString() == "CH");
                                               <text> Adults(@adults ), Children( @children )</text>
                                        }
                                                      }*@
                                </td>
                            </tr>

                            @for (int rk = 0; room.rates != null && rk < room.rates.Count && String.IsNullOrEmpty(rateKey); rk++)
                            {
                                var roomtype = room.rates[rk];
                                
                                <tr>
                                    <td>

                                        <input data-role="none" type="radio" id="roomtype-@hotel.code-@r-@rk" name="roomtype-roomtype-@hotel.code-@r-@rk" hotelcode="@hotel.code" roomcode="@room.code" @((r == 0) ? "checked" : "") roomratekey="@roomtype.rateKey" />
                                        <input id="ratekey-@hotel.code-@r-@rk" name="ratekey-@hotel.code-@r-@rk" type="hidden" value="@roomtype.rateKey" />
                                    </td>
                                    <td>
                                        @*rateKey: @roomtype.rateKey*@  @room.code (@roomtype.boardName)  @roomtype.sellingRate  <text></text>

                                    </td>
                                </tr>
                            }
                        </table>
                    }
                    }



                </td>
            </tr>
            <tr>
                <td>
                    @*@{if (hotel.IsBookOnline) {*@
                    <input type="submit" value="Book Online" />
                    @* }else
                         {<input type="submit" value ="Request Holiday" disabled =true />  }
                        }*@
                </td>
            </tr>
            <tr>
                <td></td>
            </tr>
        </table>
    //</form>
    }
}